### PR TITLE
fix: upgrade checkout to v3

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
@msvticket how about just removing github workflow for PR? The docker build step wont work anyways, as we are not pushing a binary, and all the other steps are anyways in the jx pr pipeline ...

**Comment by msvticket** [comment]
> @msvticket how about just removing github workflow for PR? The docker build step wont work anyways, as we are not pushing a binary, and all the other steps are anyways in the jx pr pipeline ...

Fine with me

**Comment by msvticket** [comment]
I can do it in my pr

**Pull request closed without merging**
