### PR TITLE
chore:upgraded to 1.22

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**
related to jenkins-x/jx#8670

### CODE REVIEW

**Review by msvticket — CHANGES_REQUESTED** [review]
Thank you for the PR!

As it says in https://jenkins-x.io/community/maintainer_guide/go-upgrades/ you should upgrade all jx dependencies. (Preferably you should also upgrade other dependencies.) You haven't upgraded jx-helpers and jx-kube-client.

**Comment by 7h3-3mp7y-m4n** [comment]
Okay, thanks @msvticket , I'll fix it ASAP

**Comment by msvticket** [comment]
> @7h3-3mp7y-m4n: The following tests **failed**, say `/retest` to rerun them all:
> Test name 	Commit 	Details 	Rerun command
> lint 	[f835a1f](https://github.com/jenkins-x/jx-git-operator/commit/f835a1f6ac310b33d8d5beb8f4975a065781126d) 	[link](http://dashboard-jx.infra.jenkins-x.rocks/namespaces/jx/pipelineruns/ns-x-jx-git-operator-pr-222-lint-27tq6) 	`/test lint`
> pr 	[f835a1f](https://github.com/jenkins-x/jx-git-operator/commit/f835a1f6ac310b33d8d5beb8f4975a065781126d) 	[link](http://dashboard-jx.infra.jenkins-x.rocks/namespaces/jx/pipelineruns/kins-x-jx-git-operator-pr-222-pr-sh9zd) 	`/test pr`

**Pull request merged**
