### PR TITLE
Updated go version to 1.19 in jx-git-operator

### PR DESCRIPTION
**Pull request by PratikforCoding**
Signed-off-by: PratikforCoding <kotalpratik@gmail.com>

### CODE REVIEW

**Comment by PratikforCoding** [comment]
related to jenkins-x/jx#8433

**Comment by PratikforCoding** [comment]
@msvticket sir there is a sign in option when i tried to see the details of the failed check. From where do I need to make a account? Can you please help me?

**Comment by ankitm123** [comment]
lint failures:
```


pkg/launcher/job/job_launcher.go:6:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
--
  |   |   |   | "io/ioutil"
  |   |   |   | ^
  |   |   |   | pkg/poller/poller.go:4:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
  |   |   |   | "io/ioutil"
  |   |   |   | ^
  |   |   |   | pkg/launcher/job/job_launcher_test.go:5:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
  |   |   |   | "io/ioutil"
  |   |   |   | ^


```

**Comment by ankitm123** [comment]
Run make lint locally to reproduce the error.

**Comment by msvticket** [comment]
Duplicate of #211

**Pull request closed without merging**
