### PR TITLE
fix: boot jobs running in parallel

### LINKED ISSUE #193: jx-boot jobs run in parallel
jx-boot jobs can run in parallel, which shouldn't happen. Here is an example where you can see that the pod for a job (jx-boot-4232f46b-2796-4126-a5d1) is created while a previous job (jx-boot-e37a7a2d-3740-48ec-9687) is not done. I think it only happens when the pods for a job fail.

```
$ kubectl get pods  --sort-by '{.metadata.creationTimestamp}' -l app=jx-boot
NAME                                                 READY   STATUS      RESTARTS   AGE
jx-boot-e37a7a2d-3740-48ec-9687-39a0023c9f0a-4r5s2   0/1     Error       0          44m
jx-boot-e37a7a2d-3740-48ec-9687-39a0023c9f0a-qvs5b   0/1     Error       0          43m
jx-boot-e37a7a2d-3740-48ec-9687-39a0023c9f0a-b7hrw   0/1     Error       0          42m
jx-boot-e37a7a2d-3740-48ec-9687-39a0023c9f0a-d9sjj   0/1     Error       0          39m
jx-boot-4232f46b-2796-4126-a5d1-cc5dbbb6d458-h5rpb   0/1     Completed   0          37m
jx-boot-e37a7a2d-3740-48ec-9687-39a0023c9f0a-7zlhg   0/1     Error       0          36m
jx-boot-a43d0365-21a6-4dc3-a55c-bf9fd525fd86-cvb5v   0/1     Completed   0          33m
```

jx-git-operator version: 0.0.194

### PR DESCRIPTION
**Pull request by msvticket**
Fixes #193

### CODE REVIEW

**Comment by msvticket** [comment]
@ankitm123 I don't know to fix jenkins-x-pr.yaml, do you know? And by the way: Do you know how it's configured that https://github.com/jx3-gitops-repositories/jx3-github.git is used as the cluster repo?

**Comment by ankitm123** [comment]
> how to fix jenkins-x-pr.yaml

You can upgrade github checkout actions to v3 (seems like I only did it for release 🤦 ), and it will fix the issue.

**Comment by ankitm123** [comment]
> Do you know how it's configured that https://github.com/jx3-gitops-repositories/jx3-github.git is used as the cluster repo

No idea, where did u see that?

**Comment by msvticket** [comment]
> > Do you know how it's configured that https://github.com/jx3-gitops-repositories/jx3-github.git is used as the cluster repo
> 
> No idea, where did u see that?

In this output: https://github.com/jenkins-x/jx-git-operator/runs/7591873207?check_suite_focus=true

**Comment by msvticket** [comment]
> > how to fix jenkins-x-pr.yaml
> 
> You can upgrade github checkout actions to v3 (seems like I only did it for release 🤦 ), and it will fix the issue. Check the issue here: https://github.com/jenkins-x/jx/blob/ca7cf32a330c63c46187f9b03280c5a72f96cae0/.github/workflows/jenkins-x/upload-binaries.sh#L3

No, the release uses v2 as well and apparently works: https://github.com/jenkins-x/jx-git-operator/runs/7377621254?check_suite_focus=true

**Comment by ankitm123** [comment]
ur right, I confused it with docker checkout, let me take a look.

**Comment by ankitm123** [comment]
btw, how are the jobs even running for ur PR? Mine dont run, seems ur not on a fork ...

**Comment by ankitm123** [comment]
Ugly hack: #204

**Pull request merged**
